### ISSUE TITLE
Unable to convert Context to json

### ISSUE THREAD

**Issue by AlonKapi** [watson-developer-cloud/java-sdk#1076]
**Overview**
Trying to use assistant version 7.1.0 and up, I'm unable to to convert Context objects to json using Gson.

**Expected behavior**
Working as intended on 6.x.x versions.

**Actual behavior**
Getting error:
`Caused by: java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: java.lang.Object. Forgot to register a type adapter?
	at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:73)
	at com.google.gson.internal.bind.TypeAdapters$1.write(TypeAdapters.java:69)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
...`

**How to reproduce**
Just using:
`Gson gson = new Gson();
String json = gson.toJson(context);`
Where context is an object of type com.ibm.watson.assistant.v1.model.Context;

**SDK Version**
Tried all 7.x.x versions.

**Comment by lpatino10** [comment]
Hey @AlonKapi, thanks for bringing this up. I'll take a look and see what we can do.

**Comment by lpatino10** [comment]
We have some special Gson adapters in place to do serialization/deserialization of our models, so I can confirm that the base Gson object doesn't work for something like `Context`. The Gson setup we have with the registered adapters is available with the following:

```java
import com.ibm.cloud.sdk.core.util.GsonSingleton;
.
.
.
Context context = response.getContext();
String contextJson = GsonSingleton.getGson().toJson(context);
System.out.println("JSON string: " + contextJson);
```

That should be available everywhere and will give you the result you're looking for!
