### ISSUE TITLE
Discovery Query IllegalStateException

### ISSUE THREAD

**Issue by jchblsc** [watson-developer-cloud/java-sdk#1085]
**Overview**
Discovery query result causes `IllegalStateException` with 7.4.0.  The same code works fine with 6.14.0. (after removing `.getResult()`).  Also, the JSON returned by the corresponding curl command appears to parse correctly when saved and opened by Firefox.

**The Error**
```
Sep 09, 2019 3:03:34 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://iam.cloud.ibm.com/identity/token http/1.1 (135-byte body)
Sep 09, 2019 3:03:34 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK https://iam.cloud.ibm.com/identity/token (371ms, 1800-byte body)
Sep 09, 2019 3:03:34 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://gateway.watsonplatform.net/discovery/api/v1/environments/*obfuscated*/collections/*obfuscated*/query?version=2019-04-30 http/1.1 (68-byte body)
Sep 09, 2019 3:03:35 PM okhttp3.internal.platform.Platform log
INFO: <-- 200 OK https://gateway.watsonplatform.net/discovery/api/v1/environments/*obfuscated*/collections/*obfuscated*/query?version=2019-04-30 (970ms, unknown-length body)
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3559 path $.results[0].title
	at com.ibm.cloud.sdk.core.util.DynamicModelTypeAdapterFactory$Adapter.read(DynamicModelTypeAdapterFactory.java:395)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.ibm.cloud.sdk.core.util.ResponseUtils.getValue(ResponseUtils.java:148)
	at com.ibm.cloud.sdk.core.util.ResponseConverterUtils$6.convert(ResponseConverterUtils.java:136)
	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:471)
	at com.ibm.cloud.sdk.core.service.BaseService$WatsonServiceCall.execute(BaseService.java:544)
	at jch.watson.localdocs.NLQueryMain.main(NLQueryMain.java:26)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 3559 path $.results[0].title
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.ibm.cloud.sdk.core.util.DynamicModelTypeAdapterFactory$1.read(DynamicModelTypeAdapterFactory.java:270)
	at com.ibm.cloud.sdk.core.util.DynamicModelTypeAdapterFactory$Adapter.read(DynamicModelTypeAdapterFactory.java:377)
	... 11 more
```
**Code**
```
public static void main(String[] args)
	{
		IamOptions options = new IamOptions.Builder().apiKey(Const.apiKey).build();
		Discovery discovery = new Discovery("2019-04-30", options);

		String environmentId = Const.environmentID;
		String collectionId = Const.collectionID;

		QueryOptions.Builder queryBuilder = new QueryOptions.Builder(environmentId, collectionId);
		queryBuilder.naturalLanguageQuery("*some query string*");
		queryBuilder.passages(false);
		queryBuilder.count(6);
		
		QueryResponse queryResponse = discovery.query(queryBuilder.build()).execute().getResult();
```

**SDK Version**
ibm-watson-7.4.0-jar-with-dependencies.jar

**Additional information:**
- OS: Windows 10
- jre1.8.0_202

**Comment by lpatino10** [comment]
Hi @jchblsc, thanks for the submission. This issue sounds the same to me as https://github.com/watson-developer-cloud/java-sdk/issues/1058, which we unfortunately don't have a solution for yet 😕 

Just to verify, are you by any chance trying this query on a collection with a Smart Document Understanding (SDU) model?

**Comment by jchblsc** [comment]
Yes, it is an SDU model.

**Comment by lpatino10** [comment]
Unfortunately the way the API is defined for that case currently, it's not compatible with the SDK 😞  We've let the Discovery team know about it but there's no immediate timetable for a fix.

**Comment by jchblsc** [comment]
That seems weird since it does work using SDK 6.14.

**Comment by lpatino10** [comment]
Yeah that is strange... We made a small tweak to the deserialization library with the jump to 7.x.x that was supposed to be backwards-compatible, but maybe the old way happened to handle this case.

I can take a closer look at it when I get the chance.

**Comment by lpatino10** [comment]
It looks like this should be cleared up in the upcoming release. The Discovery API team has confirmed that the `title` field is incorrectly specified at the moment and should be placed in the dynamic `additional_properties` section of the response, which won't break deserialization.

**Comment by lpatino10** [comment]
This issue should be cleared up in v8.1.0.
