### ISSUE TITLE
Discovery HTTP 404 retrieving Stop Words

### ISSUE THREAD

**Issue by jchblsc** [watson-developer-cloud/java-sdk#1086]
**Overview**
Unable to retrieve stops words using SDK 7.4.0 or 6.14.0.  The associated curl command also fails.  

**Error**
```
INFO: --> GET https://gateway.watsonplatform.net/discovery/api/v1/environments/*obfuscated*/collections/*obfuscated*/word_lists/stopwords?version=2019-04-30 http/1.1
Sep 09, 2019 4:32:46 PM okhttp3.internal.platform.Platform log
INFO: <-- 404 Not Found https://gateway.watsonplatform.net/discovery/api/v1/environments/*obfuscated*/collections/*obfuscated*/word_lists/stopwords?version=2019-04-30 (129ms, 66-byte body)
Sep 09, 2019 4:32:46 PM com.ibm.watson.developer_cloud.service.WatsonService processServiceCall
SEVERE: GET https://gateway.watsonplatform.net/discovery/api/v1/environments/*obfuscated*/collections/*obfuscated*/word_lists/stopwords?version=2019-04-30, status: 404, error: {"status":"not found","type":"stopwords"}
Exception in thread "main" com.ibm.watson.developer_cloud.service.exception.NotFoundException: {"status":"not found","type":"stopwords"}
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:511)
	at com.ibm.watson.developer_cloud.service.WatsonService$WatsonServiceCall.execute(WatsonService.java:567)
	at jch.watson.localdocs.StopWordListStatusMain.main(StopWordListStatusMain.java:30)
```

**How to reproduce**
Call the API as documented in the API doc.  
```java
IamOptions options = new IamOptions.Builder().apiKey(Const.apiKey).build();
		Discovery discovery = new Discovery("2019-04-30", options);

		String environmentId = Const.environmentID;
		String collectionId = Const.collectionID;

		GetStopwordListStatusOptions swlOptions = new GetStopwordListStatusOptions.Builder()
		  .environmentId(environmentId)
		  .collectionId(collectionId)
		  .build();

		TokenDictStatusResponse response = discovery.getStopwordListStatus(swlOptions).execute();
//		TokenDictStatusResponse response = discovery.getStopwordListStatus(swlOptions).execute().getResult();

		System.out.println(response);
```
or via `curl`

```
curl -u "apikey":"*obfuscated*" -X GET "https://gateway.watsonplatform.net/discovery/api/v1/environments/*obfuscated*/collections/*obfuscated*/word_lists/stopwords?version=2019-04-30"
```

**SDK Version**
7.4.0 and 6.14.0.

**Additional information:**
- OS: Windows 10
- jre1.8.0_202

**Comment by germanattanasio** [comment]
@maniax89 do you think you can take a look at this? It looks like the curl command is failing too so it could be a service issue

**Comment by maniax89** [comment]
First off, I would make sure you have already uploaded a stopword list before attempting to retrieve it's status.

If curl is still failing after uploading a stopword list, I would open a support ticket at https://watson.service-now.com/wcp with your environment and collection ids so that a member can look into the logs to help diagnose the issue.

**Comment by jchblsc** [comment]
I have not loaded stopwords.  I will assume that the Discovery team has intentionally used HTTP 404 as the way to indicate that no stopword list has been uploaded.
