### ISSUE TITLE
Investigate `OutOfMemoryError` when making multi-threaded `recognize()` calls on v8.0.0

### ISSUE THREAD

**Issue by lpatino10** [watson-developer-cloud/java-sdk#1094]
This issue was reported by someone working with a client. Their full transcript is below:

---

They have a process in which they’re requesting transcripts from the service and renaming the audio file. They’re receiving two separate errors.
1. A File Exception error, which happens after they receive transcripts and attempt to rename the file:
```
Exception in thread "main" java.nio.file.FileSystemException: {FILENAME} -> {NEW_FILENAME}: The process cannot access the file because it is being used by another process.
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
at java.nio.file.Files.move(Files.java:1395)
at com.principal.analytics.Driver$.main(Driver.scala:24)
at com.principal.analytics.Driver.main(Driver.scala)
```
(Note, they were able to resolve this by closing the InputStream returned by RecognizeOptions.audio(), after calling ServiceCall.execute().)
2. And a second `OutOfMemoryError` when multi-threading, submitting around 40 files.
```
java.lang.OutOfMemoryError: Java heap space
```
They do not receive any transcripts when this error is encountered.

Their process is multi-threaded with up to 500 threads. It creates a Singleton instance of `AuthenticatedSpeechToTex`t & then calls the `recognize()` method for each file.
For renaming, they are using the standard `java.nio.file.Files.move()` method referenced in the StackTrace above. They also attached the `AuthenticatedSpeechToText` class.

---

They've sent me the referenced Java class. The first issue they mention seems like it might have just been an implementation issue, but I need to investigate what might've changed since v7.3.0 to have issues with multi-threaded STT calls.

**Comment by lpatino10** [comment]
Testing so far, I unfortunately haven't been able to replicate the `OutOfMemoryError` 😞  It's possible that this is a hardware constraint on my end, since trying to send that many files for me has resulted in timeouts from the Speech to Text service or my internet just cutting out.
