### ISSUE TITLE
Discovery rejects a file with French characters in the file name.

### ISSUE THREAD

**Issue by Brian-Woodsworth** [watson-developer-cloud/java-sdk#1115]
**Overview**
I have been working on a java program to upload files from a folder into a collection in Watson Discovery. The program is designed to upload English documents to a English collection and French documents to a French collection. The same code is used to add and update the documents to either collection.

The English documents upload fine, but when a French document with French characters in the filename is uploaded the file is rejected with the following exception: 

```
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected char 0xe9 at 49 in Content-Disposition value: form-data; name="file"; filename="Architecture, génie et arpentage.pdf"
	at okhttp3.Headers.checkValue(Headers.java:272)
	at okhttp3.Headers.of(Headers.java:224)
	at okhttp3.MultipartBody$Part.createFormData(MultipartBody.java:259)
	at okhttp3.MultipartBody$Builder.addFormDataPart(MultipartBody.java:324)
	at com.ibm.watson.discovery.v1.Discovery.addDocument(Discovery.java:1092)
	at com.ibm.agentassist.scheduler.WDSDocumentAPICalls.addDocumentWithMetaData(WDSDocumentAPICalls.java:127)
	at com.ibm.agentassist.scheduler.WDSMainUtils.runInitialLoad(WDSMainUtils.java:289)
	at com.ibm.agentassist.scheduler.WDSMainProgram.main(WDSMainProgram.java:425)
```

I changed the filename to one without any French characters and it uploaded without any issue.

**Expected behavior**

I would expect that the filename with French characters is uploaded without an issue.

**Actual behavior**

The file was rejected.

**How to reproduce**

I have provided the class file with the method that uploads the file along with the files it loads without issue and the files that failed. You would need to use the Add Document API to upload one of the files that failed to reproduce the issue.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**

ibm-watson-8.2.1-jar-with-dependencies

**Additional information:**
 jre1.8.0_241

**Additional context**
[French File Name Issue.zip](https://github.com/watson-developer-cloud/java-sdk/files/4403746/French.File.Name.Issue.zip)

**Comment by mediumTaj** [comment]
Still active

**Comment by mediumTaj** [comment]
Is this still an issue?

**Comment by Brian-Woodsworth** [comment]
No, That project was put on hold.
