### ISSUE TITLE
[Text-to-Speech] Exception in provided example

### ISSUE THREAD

**Issue by jackpeters667** [watson-developer-cloud/java-sdk#1149]
Hi there, I'm failing to get the example running on my application. I'm using 

- JavaFX 15.0.1 (Gradle)
- JDK 15.0.1

And in my dependency list, I have:

-   'com.ibm.cloud:sdk-core:9.5.3'
-   'com.ibm.watson:ibm-watson:9.0.2'

My stacktrace outputs:

`Caused by: com.ibm.cloud.sdk.core.service.exception.ForbiddenException: Forbidden
Caused by: com.ibm.cloud.sdk.core.service.exception.ForbiddenException: Forbidden

	at com.ibm.cloud.sdk.core.service.BaseService.processServiceCall(BaseService.java:388)
	at com.ibm.cloud.sdk.core.service.BaseService$WatsonServiceCall.execute(BaseService.java:436)
	at com.tts.controller.Controller.initialize(Controller.java:70)
	at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2655)`

And my code is 
`
        Authenticator authenticator = new IamAuthenticator(API_KEY);
        TextToSpeech service = new TextToSpeech(authenticator);
        Voices voices = service.listVoices().execute().getResult(); //This is my line 70
        System.out.println(voices);
`
Any help would be appreciated. I found a project somewhere using TTS and my credentials work fine on it, but I can't get this example to work.

**Comment by jackpeters667** [comment]
I had to use `.setServiceURL();` please include that in the docs too.
