### ISSUE TITLE
Gson 2.8.9 java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by HidekiMori** [watson-developer-cloud/java-sdk#1195]
(I apologize if I have read the posting rules because I don't understand English enough.)

Hi, it's just a report, not a bug.

When I use Gson updated to 2.8.9, I get the following error :

java.lang.RuntimeException: Error while fetching access token from token service: 
	at com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator.getToken(TokenRequestBasedAuthenticator.java:222)
	at com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator.authenticate(TokenRequestBasedAuthenticator.java:160)
	at com.ibm.cloud.sdk.core.service.BaseService.setAuthentication(BaseService.java:363)
	at com.ibm.cloud.sdk.core.service.BaseService.createCall(BaseService.java:301)
	at com.ibm.cloud.sdk.core.service.BaseService.createServiceCall(BaseService.java:339)
	at com.ibm.watson.language_translator.v3.LanguageTranslator.listLanguages(LanguageTranslator.java:177)
	at com.ibm.watson.language_translator.v3.LanguageTranslator.listLanguages(LanguageTranslator.java:192)
	at MyApplication.test(MyApplication.java:149)
	... 1 more
Caused by: java.lang.NoSuchFieldError: NUMBER
	at com.ibm.cloud.sdk.core.util.GsonSingleton.registerTypeAdapters(GsonSingleton.java:66)
	at com.ibm.cloud.sdk.core.util.GsonSingleton.createGson(GsonSingleton.java:45)
	at com.ibm.cloud.sdk.core.util.GsonSingleton.getGsonWithoutPrettyPrinting(GsonSingleton.java:94)
	at com.ibm.cloud.sdk.core.util.ResponseUtils.getValue(ResponseUtils.java:149)
	at com.ibm.cloud.sdk.core.util.ResponseConverterUtils$6.convert(ResponseConverterUtils.java:137)
	at com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator$2.run(TokenRequestBasedAuthenticator.java:279)
	at java.base/java.lang.Thread.run(Thread.java:834)

There are no errors in Gson2.8.8.
It may be fixed in the next version of Gson.

os: macOS Monterey 12.0.1
openjdk: "11.0.11" 2021-04-20
sdk: 9.3.0

Thanks.

**Comment by manish-bansal** [comment]
Please update the core sdk to latest. Core already has fix for it.

**Comment by HidekiMori** [comment]
Thank you for your advice.
I have confirmed that the following set works.

sdk 9.3.0
sdk-core 9.15.0
gson 2.8.9
