### ISSUE TITLE
speechToText api : UnknownHostException: Unable to resolve host "stream.watsonplatform.net"

### ISSUE THREAD

**Issue by psbots** [watson-developer-cloud/java-sdk#176]
when running v 2.6.0 (due to this [bug](https://github.com/watson-developer-cloud/java-sdk/issues/167)
on calling the SpeechToText API as shown in the example code, I get the following error :

```
E/WatsonService: IOException
java.net.UnknownHostException: Unable to resolve host "stream.watsonplatform.net": No address associated with hostname
  at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
  at java.net.InetAddress.getAllByName(InetAddress.java:215)
  at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
  at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
  at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
  at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
  at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
  at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
  at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
  at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
  at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
  at com.squareup.okhttp.Call.getResponse(Call.java:286)
  at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
  at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
  at com.squareup.okhttp.Call.execute(Call.java:80)
  at com.ibm.watson.developer_cloud.service.WatsonService.execute(WatsonService.java:121)
  at com.ibm.watson.developer_cloud.service.WatsonService.executeRequest(WatsonService.java:182)
  at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.recognize(SpeechToText.java:285)
  at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToText.recognize(SpeechToText.java:244)
  at in.psbots.storyinsights.MainActivity$speechToText.doInBackground(MainActivity.java:87)
  at in.psbots.storyinsights.MainActivity$speechToText.doInBackground(MainActivity.java:78)
  at android.os.AsyncTask$2.call(AsyncTask.java:292)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
 Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
  at libcore.io.Posix.android_getaddrinfo(Native Method)
  at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
  at java.net.InetAddress.lookupHostByName(InetAddress.java:438
```

**Comment by germanattanasio** [comment]
I'm not able to reproduce your issue. Can you try again and maybe copy the code you are using.

**Comment by hcsekaran** [comment]
Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException: Failed to connect to stream.watsonplatform.net/158.85.132.94:443
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:172)
	at com.ibm.watson.developer_cloud.speech_to_text.v1.SpeechToTextExample.main(SpeechToTextExample.java:32)
Caused by: java.net.ConnectException: Failed to connect to stream.watsonplatform.net/158.85.132.94:443
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:142)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at okhttp3.RealCall.getResponse(RealCall.java:240)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:169)
	... 1 more
I am unable to connect the IBM Watson server stream.watsonplatform.net, while running the SpeechToText Sample Application from java sdk. please help me to resolve the issue

**Comment by germanattanasio** [comment]
I don't think this is related to the java-sdk. I just tried and it seems to be working

**Comment by jpreisner** [comment]
Hi @germanattanasio , I have the same problem that @hcsekaran. This problem is related to the proxy. What is strange is that this problem does not occur in Python with Python SDK.

Do you know why?

Thanks.

**Comment by jpreisner** [comment]
To fix the problem of @hcsekaran : 

System.setProperty("http.proxyHost",host);
    	System.setProperty("http.proxyPort",port);

    	System.setProperty("https.proxyHost",host);
    	System.setProperty("https.proxyPort",port);

**Comment by germanattanasio** [comment]
this is related to #311

**Comment by Danilo-Araujo-Silva** [comment]
If we are not using proxy, how can we handle this?

I'm receiving this error and I'm using the most recent version of the watson sdk.

**Comment by Danilo-Araujo-Silva** [comment]
I was able to solve the problem using this:

```
System.setProperty("http.proxyHost","");
System.setProperty("http.proxyPort","");
System.setProperty("https.proxyHost","");
System.setProperty("https.proxyPort","");
```

It's kind of crazy since I'm not really using proxies.
