### ISSUE TITLE
android.os.NetworkOnMainThreadException crashed Android App 

### ISSUE THREAD

**Issue by shenybluemix** [watson-developer-cloud/java-sdk#178]
Using SDK 2.6 to call Alchemy Sentiment Analysis.  Running the sample code in README.  The whole Android App (Android SDK 23 ) is crashed when because of                                                                     android.os.NetworkOnMainThreadException  ( looks like from okhttp library) when calling getSentiment() function.   

```
02-04 23:40:39.200 26642-26642/ibm.us.com.fashionx E/AndroidRuntime: FATAL EXCEPTION: main
 Process: ibm.us.com.fashionx, PID: 26642
 android.os.NetworkOnMainThreadException
     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
     at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
     at java.net.InetAddress.getAllByName(InetAddress.java:215)
     at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
     at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
     at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
     at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
     at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
     at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
     at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
     at com.squareup.okhttp.Call.getResponse(Call.java:286)
     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
     at com.squareup.okhttp.Call.execute(Call.java:80)
     at com.ibm.watson.developer_cloud.service.WatsonService.execute(WatsonService.java:121)
     at com.ibm.watson.developer_cloud.service.AlchemyService.execute(AlchemyService.java:106)
     at com.ibm.watson.developer_cloud.service.AlchemyService.executeRequest(AlchemyService.java:135)
     at com.ibm.watson.developer_cloud.alchemy.v1.AlchemyLanguage.executeRequest(AlchemyLanguage.java:107)
     at com.ibm.watson.developer_cloud.alchemy.v1.AlchemyLanguage.getSentiment(AlchemyLanguage.java:243)
     at ibm.us.com.fashionx.MainActivity$6.onClick(MainActivity.java:290)
     at android.view.View.performClick(View.java:5204)
     at android.view.View$PerformClick.run(View.java:21153)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-04 23:40:39.203 26642-26716/ibm.us.com.fashionx E/com.ibm.mobilefirstplatform.clientsdk.android.logger.api.Logger$UncaughtExceptionHandler: Logger$UncaughtExceptionHandler.uncaughtException in Logger.java:316 :: Uncaught Exception
    
```

**Comment by shenybluemix** [comment]
The sample code I am running in my Android App is as follows
```
AlchemyLanguage alchemyService = new AlchemyLanguage();        
alchemyService.setApiKey("**************");
GenericCache.getInstance().put("AlchemySerivce", alchemyService);
Map<String,Object> params = new HashMap<String, Object>();
params.put(AlchemyLanguage.TEXT, "I feel good today");
DocumentSentiment sentiment = alchemyService.getSentiment(params);`
```

**Comment by shenybluemix** [comment]
B.T.W I am using SDK 2.6 because I met the issue #167

**Comment by VidyasagarMSC** [comment]
Starting from HoneyComb (SDK 3.0), Android throws this **NetworkOnMainThreadException** if a long operation such as network access or database query is using it's **Main Thread** aka UI Thread. 

One fix which I can think of is running your code in **AsyncTask**.

**Note:** Luckily , okHTTP doesn't use Apache HTTPClient which is deprecated effective API 23/ Android SDK 6.0

**Comment by germanattanasio** [comment]
As @VidyasagarMSC said. You need to run the code in a different Thread.

```
Thread thread = new Thread(new Runnable(){
  public void run() {
    try {
      AlchemyLanguage alchemyService = new AlchemyLanguage();
      alchemyService.setApiKey("**************");

      Map<String,Object> params = new HashMap<String, Object>();
      params.put(AlchemyLanguage.TEXT, "I feel good today");
      DocumentSentiment sentiment = alchemyService.getSentiment(params);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
});

thread.start();
```

**Comment by esdrasdemorais** [comment]
AssyncTask is more recommended:
https://developer.android.com/training/articles/perf-anr
