### ISSUE TITLE
How to perform a query using AlchemyDataNews API like this?

### ISSUE THREAD

**Issue by shikida** [watson-developer-cloud/java-sdk#213]
https://access.alchemyapi.com/calls/data/GetNews?apikey=YOUR_API_KEY_HERE&return=enriched.url.title,enriched.url.publicationDate,enriched.url.enrichedTitle.docSentiment&start=1457308800&end=1457996400&q.enriched.url.enrichedTitle.entities.entity=|text=IBM,type=company|&q.enriched.url.enrichedTitle.taxonomy.taxonomy_.label=technology%20and%20computing&count=25&outputMode=json

I was trying

		String[] fields =
		    new String[] {"enriched.url.title", "enriched.url.url", "enriched.url.author",
		        "enriched.url.publicationDate", "enriched.url.enrichedTitle.entities",
		        "enriched.url.enrichedTitle.docSentiment"};
		params.put(AlchemyDataNews.RETURN, StringUtils.join(fields, ","));
		params.put(AlchemyDataNews.START, "1440720000");
		params.put(AlchemyDataNews.END,   "1441407600");
		params.put(AlchemyDataNews.COUNT, 7);
		params.put("q.enriched.url.enrichedTitle.entities.entity","|text=IBM");
		params.put("type","company");
		params.put("q.enriched.url.enrichedTitle.taxonomy.taxonomy_.label","technology%20and%20computing");

but I've got

Mar 13, 2016 10:46:49 PM com.ibm.watson.developer_cloud.service.AlchemyService execute
SEVERE: {"error":"Invalid key enriched.url.enrichedTitle.entities.entity","code":400}
Exception in thread "main" com.ibm.watson.developer_cloud.service.BadRequestException: {"error":"Invalid key enriched.url.enrichedTitle.entities.entity","code":400}
	at com.ibm.watson.developer_cloud.service.AlchemyService.execute(AlchemyService.java:115)
	at com.ibm.watson.developer_cloud.service.AlchemyService.executeRequest(AlchemyService.java:135)
	at com.ibm.watson.developer_cloud.alchemy.v1.AlchemyDataNews.getNewsDocuments(AlchemyDataNews.java:98)
	at example.WatsonAPI.main(WatsonAPI.java:56)

How exactly do I query for specific entities using this API?

**Comment by shikida** [comment]
oh sorry

just use it like this

params.put("q.enriched.url.enrichedTitle.entities.entity","|text=IBM,type=company|");

sorry, pls close this issue
