### ISSUE TITLE
3.0.0.RC1 on Bluemix is causing trust manager issue

### ISSUE THREAD

**Issue by jconallen** [watson-developer-cloud/java-sdk#264]
When trying to use the 3.0.0.RC1 all dependencies jar, everything runs fine locally.  But when I try to deploy to a Liberty runtime on Bluemix the following error

```
java.lang.IllegalStateException: Unable to extract the trust manager on okhttp3.internal.Platform@5973f0c2, sslSocketFactory is class com.ibm.jsse2.SSLSocketFactoryImpl
at okhttp3.OkHttpClient.(OkHttpClient.java:187)
at okhttp3.OkHttpClient.(OkHttpClient.java:60)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:718)
at com.ibm.watson.developer_cloud.service.WatsonService.configureHttpClient(WatsonService.java:124)
at com.ibm.watson.developer_cloud.service.WatsonService.(WatsonService.java:103)
at com.ibm.watson.developer_cloud.language_translation.v2.LanguageTranslation.(LanguageTranslation.java:80)
at com.ibm.bluemix.MessageMaker.GetMessage(MessageMaker.java:10)
at com.ibm._jsp._index._jspService(_index.java:96)
at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:101)
at [internal classes]

```
This feels like an issue with the Bluemix JVM and the library's TrustManager.

My current workaround is to use the previous version of the library (2.10), which works fine both locally and on Bluemix.

**Comment by jconallen** [comment]
Is is possible, in the meantime, to put a link to the current GA version of this library in the Readme page.  It is actually kind of hard to find. Thanks.

**Comment by germanattanasio** [comment]
We don't have a `3.0.X` GA version yet. I think we will do a release next week that will include the fix for this issue if possible

**Comment by jconallen** [comment]
OK, I was just suggesting the 2.x GA release get a link in the readme, so new people wanting a GA library can easily find it.

**Comment by priand** [comment]
Any news on this issue? We just faced it as well.

**Comment by max-vogler** [comment]
Looks like the excellent @g-may found a solution for it in #311 

> I found this post square/okhttp#2323 (comment) and tried upgrading the okhttp dependency from 3.2.0 to 3.3.1 in pom.xml of my clone, and was able to get things working.
