### ISSUE TITLE
Skip token authentication if skipAuthentication flag is true

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/java-sdk#439]
```java
SpeechToText service = new SpeechToText();

String URL = "http://my-proxy-app:1080/speech-to-text/api";
service.setEndPoint(URL);
service.setSkipAuthentication(true);
```

The output was:
```
Listening to your voice for the next 30s...
Sep 11, 2016 8:59:48 PM com.ibm.watson.developer_cloud.service.WatsonService processServiceCall
SEVERE: GET http://my-proxy-app:1080/authorization/api/v1/token?url=http://my-proxy-app:1080/speech-to-text/api, status: 404, error: No such child resource.
Sep 11, 2016 8:59:48 PM com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.BaseRecognizeCallback onError
SEVERE: No such child resource.
com.ibm.watson.developer_cloud.service.exception.NotFoundException: No such child resource.
    at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:422)
    at com.ibm.watson.developer_cloud.service.WatsonService$1$1.onResponse(WatsonService.java:196)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
 ```
```

**Comment by germanattanasio** [comment]
fixed
