### ISSUE TITLE
[NLC] Date format error upon usage of java-sdk

### ISSUE THREAD

**Issue by asidd** [watson-developer-cloud/java-sdk#445]
Soft Bank is complaining the following:
***********************************

When using java-sdk, date format errors occurred.

I have a guess that NLC has changed date formats.
However sdk has not followed that.

Old     : 2016-06-20T04:25:16.218+0000
Current : Reference：2015-05-28T18:01:57.393Z

IBM has published the sdk in formal doc.
Could you update doc or sdk to normal one with no errors.
*****************************************************

They are using versions java-sdk-2.8.0 and 3.0.0.
They are requesting us to investigate version 2.0.0 which was officially announced at https://www.ibm.com/watson/developercloud/natural-language-classifier/api/v1/

Here is the error they see:
************************

Error parsing: 2016-06-20T04:25:16.218+0000

java.text.ParseException: Unparseable date: "2016-06-20T04:25:16.218+0000"

at java.text.DateFormat.parse(DateFormat.java:366)

at com.ibm.watson.developer_cloud.util.DateDeserializer.deserialize(DateDeserializer.java:66)

at com.ibm.watson.developer_cloud.util.DateDeserializer.deserialize(DateDeserializer.java:31)

at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)

at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:52)

at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)

at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)

at com.google.gson.Gson.fromJson(Gson.java:810)

at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:90)

at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)

at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:73)

at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:363)

**Comment by germanattanasio** [comment]
2.X is ~ 8 months old. We are not supporting 2.X versions anymore.

**Comment by asidd** [comment]
German,

API Reference has the following dependency mentioned:

<dependency>
  <groupId>com.ibm.watson.developer_cloud</groupId>
  <artifactId>java-sdk</artifactId>
  <version>2.0.0</version>
</dependency>

**Comment by germanattanasio** [comment]
I understand. I will talk to the documentation team to update that.

**Comment by germanattanasio** [comment]
The documentation will be updated soon. @SirSpidey is working on it

**Comment by asidd** [comment]
Softbank has comeback stating that they are experiencing this issue with java-sdk 3.x.

**Comment by asidd** [comment]
@kognate @germanattanasio 
any updates on this issue in regards to java-sdk 3.x ?

**Comment by germanattanasio** [comment]
@asidd we have a test written by @kognate that tests the same date you have in your error and it's passing. We need to know which version is softbank using.

**Comment by asidd** [comment]
@germanattanasio 
Client is using java-sdk 3.0.0

**Comment by germanattanasio** [comment]
Can they move to 3.4.0?
