### ISSUE TITLE
[Discovery] Query execution fails with RuntimeException if query string contains '|' character

### ISSUE THREAD

**Issue by mwakao** [watson-developer-cloud/java-sdk#654]
The following code using Discovery service Java Client API fails with error.
If I change the query to just "author", it works fine. 

```
import com.ibm.watson.developer_cloud.discovery.v1.Discovery;
import com.ibm.watson.developer_cloud.discovery.v1.model.query.QueryRequest;
import com.ibm.watson.developer_cloud.discovery.v1.model.query.QueryResponse;
import com.ibm.watson.developer_cloud.http.ServiceCall;

public class DiscoveryTest {
    static private String endPoint = "https://gateway.watsonplatform.net/discovery/api";
    static private String username = "[User name]";
    static private String password = "[Password]";
    static private String environmentId = "[Environment ID]";
    static private String collectionId = "[Collection ID]";

//    static private String query = "author";
    static private String query = "author|writer";
    
    static public void main(String args[]){
        Discovery service = new Discovery("2016-12-11");
        service.setEndPoint(endPoint);
        service.setUsernameAndPassword(username, password);
        
        QueryRequest.Builder builder = new QueryRequest.Builder(environmentId, collectionId);
        QueryRequest queryRequest = builder.query(query).build();
        
        ServiceCall<QueryResponse> call = service.query(queryRequest);
        QueryResponse response = call.execute();
        
        System.out.println(response.toString());
    }
}

```
- Expected behavior
The query is successfully executed and query result is responded.
- Actual behavior
Runtime exception
```
Exception in thread "main" java.lang.RuntimeException: Error reading the http response
	at com.ibm.watson.developer_cloud.util.ResponseUtils.getString(ResponseUtils.java:110)
	at com.ibm.watson.developer_cloud.service.WatsonService.getErrorMessage(WatsonService.java:290)
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:410)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:180)
	at DiscoveryTest.main(DiscoveryTest.java:24)
Caused by: java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.GzipSource.consumeHeader(GzipSource.java:114)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:387)
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:371)
	at okhttp3.internal.Util.bomAwareCharset(Util.java:412)
	at okhttp3.ResponseBody.string(ResponseBody.java:173)
	at com.ibm.watson.developer_cloud.util.ResponseUtils.getString(ResponseUtils.java:107)
	... 4 more
```  
- JDK version
JDK 1.8.0
- java-sdk version
3.7.0

**Comment by maniax89** [comment]
seems like @germanattanasio already opened an issue a long time ago about this https://github.com/square/okhttp/issues/1976

**Comment by mwakao** [comment]
I think https://github.com/square/okhttp/issues/1976 was a problem of okhttp3.HttpUrl#uri() . Now uri() method escapes '|'. That's fine now.

com.ibm.watson.developer_cloud.http.RequestBuilder that constructs URL in Watson SDK uses okhttp3.HttpUrl#url() method that doesn't escape '|' character. That may cause this problem.
 
See https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.html for more detail for the difference between uri and url method.

So, I think there are inconsistency between SDK implementation and Service implementation. SDK uses url() method that is less strict than uri(), but service side requires strict one. I think the same version of SDK worked fine with the discovery service until February, so service side changed something at the time.
