### ISSUE TITLE
Using the Messenger API to get the response in the Conversation TryIt Panel stopped working

### ISSUE THREAD

**Issue by klamotte** [watson-developer-cloud/java-sdk#674]
This call stopped working about a month ago
We are using Selenium to make this call
 Using -JRE - Java80

Here is the Call we are using 
```java
Messenger messenger = new Messenger(workspaceid);
MessageResponse response = messenger.getResponse(input, CONTEXT);
```
Here is the Call Stack
```
2017-04-25 14:50:51 CoreLogger [INFO]  PASS: Verify you can Open the TryIt Panel...<td align=center><a href=04251450500835.png target=_blank><img src=04251450500835.png border=1 width=24, height=16></a></td>
2017-04-25 14:54:28 CoreLogger [ERROR] javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:182)
	at com.ibm.automation.wea.conversation.api.message.Messenger.getResponse(Messenger.java:116)
	at com.ibm.automation.wea.conversation.ui.tasks.tryit.TryItTasks.continuousConversationViaApi(TryItTasks.java:199)
	at com.ibm.automation.wea.conversation.ui.tasks.tryit.TryItTasks.continuousConversationViaApi(TryItTasks.java:182)
	at com.ibm.automation.wea.conversation.ui.testcases.dialog.OrderIceCreamValidateViaApi.TestOrderIceCreamValViaApiTestCase(OrderIceCreamValidateViaApi.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.ibm.jsse2.as.a(as.java:475)
	at com.ibm.jsse2.as.i(as.java:130)
	at com.ibm.jsse2.as.a(as.java:483)
	at com.ibm.jsse2.as.startHandshake(as.java:160)
	at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
	at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
	at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at okhttp3.RealCall.getResponse(RealCall.java:243)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:179)
	... 29 more
	Suppressed: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
		... 47 more
	Caused by: java.io.EOFException: SSL peer shut down incorrectly
		at com.ibm.jsse2.a.a(a.java:114)
		at com.ibm.jsse2.as.a(as.java:268)
		... 46 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.ibm.jsse2.a.a(a.java:114)
	at com.ibm.jsse2.as.a(as.java:268)
	... 46 more
java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:182)
	at com.ibm.automation.wea.conversation.api.message.Messenger.getResponse(Messenger.java:116)
	at com.ibm.automation.wea.conversation.ui.tasks.tryit.TryItTasks.continuousConversationViaApi(TryItTasks.java:199)
	at com.ibm.automation.wea.conversation.ui.tasks.tryit.TryItTasks.continuousConversationViaApi(TryItTasks.java:182)
	at com.ibm.automation.wea.conversation.ui.testcases.dialog.OrderIceCreamValidateViaApi.TestOrderIceCreamValViaApiTestCase(OrderIceCreamValidateViaApi.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.ibm.jsse2.as.a(as.java:475)
	at com.ibm.jsse2.as.i(as.java:130)
	at com.ibm.jsse2.as.a(as.java:483)
	at com.ibm.jsse2.as.startHandshake(as.java:160)
	at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
	at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
	at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at okhttp3.RealCall.getResponse(RealCall.java:243)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:179)
	... 29 more
	Suppressed: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
		... 47 more
	Caused by: java.io.EOFException: SSL peer shut down incorrectly
		at com.ibm.jsse2.a.a(a.java:114)
		at com.ibm.jsse2.as.a(as.java:268)
		... 46 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at com.ibm.jsse2.a.a(a.java:114)
	at com.ibm.jsse2.as.a(as.java:268)
```

### When reporting a bug, please be sure to include the following:

- [ ] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [ ] Steps to reproduce
- [ ] Expected behavior
- [ ] Actual behavior
- [x] JDK version
- [ ] java-sdk version

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title starting with the service name
- [ ] A description of the problem you're trying to solve
- [ ] A suggested solution if possible

**Comment by germanattanasio** [comment]
What's the Java SDK version you are using?

**Comment by germanattanasio** [comment]
DId you try with 3.8.0 ?

**Comment by klamotte** [comment]
Is this the info you need?





Keith LaMotte
Tooling/UI Test Engineer - Watson Core
550 King Street, LKG1-Floor 1, Office # A1135C
Littleton, MA 01460 U.S.A.
email: klamotte@us.ibm.com. Tel: 978-899-3120

**Comment by klamotte** [comment]
This is our current SDK 

![eclipsesdk](https://cloud.githubusercontent.com/assets/28020257/25447336/ceea84e0-2a82-11e7-9cf0-9566751ee9cb.png)

**Comment by germanattanasio** [comment]
@klamotte that's your eclipse version not the java SDK version.

**Comment by klamotte** [comment]
Here is the SDK version
 compile group: 'com.ibm.watson.developer_cloud', name: 'conversation', version: '3.5.3'
Tim Snow tried 3.6.0 and still had the same problem
Have you tested it using SDK 3.8?

**Comment by klamotte** [comment]
Tim Snow say the updated SDK appears to be working and he going to do some more testing before he deliver it to us. Thanks
