### ISSUE TITLE
[visual-recognition] Crash on date deserialization on Android

### ISSUE THREAD

**Issue by phcannesson** [watson-developer-cloud/java-sdk#677]
I'm encountering a crash when using the visual-recognition SDK on Android devices.

A similar issue has already been submitted and resolved here : #76 

Here is the stacktrace : 
```
java.lang.IllegalArgumentException: Unknown pattern character 'X' 
at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
  at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
  at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
  at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
  at com.ibm.watson.developer_cloud.util.DateDeserializer.<init>(DateDeserializer.java:52)
  at com.ibm.watson.developer_cloud.util.GsonSingleton.registerTypeAdapters(GsonSingleton.java:53)
  at com.ibm.watson.developer_cloud.util.GsonSingleton.createGson(GsonSingleton.java:42)
  at com.ibm.watson.developer_cloud.util.GsonSingleton.getGsonWithoutPrettyPrinting(GsonSingleton.java:76)
  at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:93)
  at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:79)
  at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
  at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:479)
  at com.ibm.watson.developer_cloud.service.WatsonService$2.execute(WatsonService.java:254)`
```
It looks like it's caused by deserialization in the DateDeserializer.class.

I'm using v3.8.0 of the SDK.

Here's the code throwing the exception : 
```java
ClassifyImagesOptions options = new ClassifyImagesOptions.Builder()
  .images(image).build();
VisualClassification result = mVisualRecognition.classify(options).execute();
```

**Comment by germanattanasio** [comment]
@mkistler I think this is because Android could be using JDK 1.6 where X is not supported.

**Comment by ahmad3ttallah** [comment]
The bug still there, could you please advice?
`05-12 13:54:27.464 20232-21456/net.hopesun.dolphins E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                      Process: net.hopesun.dolphins, PID: 20232
                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
                                                                          at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
                                                                          at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
                                                                          at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
                                                                          at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:258)
                                                                          at com.ibm.watson.developer_cloud.util.DateDeserializer.<init>(DateDeserializer.java:52)
                                                                          at com.ibm.watson.developer_cloud.util.GsonSingleton.registerTypeAdapters(GsonSingleton.java:53)
                                                                          at com.ibm.watson.developer_cloud.util.GsonSingleton.createGson(GsonSingleton.java:42)
                                                                          at com.ibm.watson.developer_cloud.util.GsonSingleton.getGsonWithoutPrettyPrinting(GsonSingleton.java:76)
                                                                          at com.ibm.watson.developer_cloud.util.ResponseUtils.getObject(ResponseUtils.java:93)
                                                                          at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:79)
                                                                          at com.ibm.watson.developer_cloud.util.ResponseConverterUtils$3.convert(ResponseConverterUtils.java:76)
                                                                          at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:479)
                                                                          at com.ibm.watson.developer_cloud.service.WatsonService$2.execute(WatsonService.java:254)
                                                                          at net.hopesun.dolphins.Watson.sendImage(Watson.java:24)
                                                                          at net.hopesun.dolphins.Home$3.doInBackground(Home.java:145)
                                                                          at net.hopesun.dolphins.Home$3.doInBackground(Home.java:143)
                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) `

**Comment by germanattanasio** [comment]
@ahmad3ttallah The bug was fixed but it's in the snapshot repository not in maven central. 
Take a look at the instructions on how to use the snapshot release [here](https://github.com/watson-developer-cloud/java-sdk#development-snapshots)
