### ISSUE TITLE
[speech-to-text] Getting RuntimeException: Malformed GUID: 'en-US_BroadbandModel' when using STT in Frankfurt and customizationID

### ISSUE THREAD

**Issue by troyibm** [watson-developer-cloud/java-sdk#752]
This has something to do with STT customization and the Java SDK as I don't get any problems with using the same STT service in Frankfurt without the customization ID.  But I also don't see this problem on iOS using the same service in Frankfurt WITH the customization ID.

This also isn't particular to the speechModel shown.  I've also tried the en-UK_BroadbandModel and get the same failure.

This was working at some point on Android (a week ago).
```
java.lang.RuntimeException: Malformed GUID: 'en-US_BroadbandModel' 
at com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.SpeechToTextWebSocketListener.onMessage(SpeechToTextWebSocketListener.java:124)
  at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
  at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
  at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
  at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
  at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
```
Contact me for the STT credentials and customization ID to reproduce this problem.

I'm using the java-sdk version 3.8.1-SNAPSHOT
Android sdk 0.2.3

**Comment by germanattanasio** [comment]
@lpatino10 this could be a good issue to start getting familiar with the SDK

**Comment by zhang-w** [comment]
This was fixed by https://github.com/watson-developer-cloud/java-sdk/pull/735.

**Comment by zhang-w** [comment]
The model option was used as the customization id, that's why it complained 

"Malformed GUID: 'en-US_BroadbandModel'"

public WebSocket recognizeUsingWebSocket(final InputStream audio, final RecognizeOptions options,
      final RecognizeCallback callback) {
    ...
    ...

    if (options.customizationId() != null && !options.customizationId().isEmpty()) {
      **urlBuilder.addQueryParameter(CUSTOMIZATION_ID, options.model());**
    }

**Comment by zhang-w** [comment]
@lpatino10 Sorry, Hope you get another starting point soon :-)

**Comment by germanattanasio** [comment]
This is fixed and in `develop` will be released soon
