### ISSUE TITLE
the speech-to-text readme can not work

### ISSUE THREAD

**Issue by aximo** [watson-developer-cloud/java-sdk#760]
follow the readme and test the most simple case but fail
i use this version
```
<dependency>
        <groupId>com.ibm.watson.developer_cloud</groupId>
        <artifactId>java-sdk</artifactId>
	<version>3.8.0</version>
</dependency>
```

and my code
```
SpeechToText service = new SpeechToText();
service.setUsernameAndPassword(username, password);

File audio = new File("src/test/resources/sample1.wav");
final RecognizeOptions options = new RecognizeOptions.Builder()
	            .contentType(HttpMediaType.AUDIO_WAV)
	            .model(SpeechModel.EN_US_NARROWBANDMODEL.getName())
	            .continuous(true)
	            .inactivityTimeout(500)
	            .build();
		
	
SpeechResults transcript = service.recognize(audio,options).execute();
```
i down the simple1.wav from this git repo

and the error is
```
Aug 16, 2017 3:03:18 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?continuous=true&inactivity_timeout=500&model=en-US_NarrowbandModel http/1.1 (80857-byte body)
Aug 16, 2017 3:03:19 PM okhttp3.internal.platform.Platform log
INFO: <-- 400 Bad Request https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?continuous=true&inactivity_timeout=500&model=en-US_NarrowbandModel (1476ms, unknown-length body)
Aug 16, 2017 3:03:19 PM com.ibm.watson.developer_cloud.service.WatsonService processServiceCall
SEVERE: POST https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?continuous=true&inactivity_timeout=500&model=en-US_NarrowbandModel, status: 400, error: unable to transcode data stream audio/wav -> audio/x-float-array 
Exception in thread "main" com.ibm.watson.developer_cloud.service.exception.BadRequestException: unable to transcode data stream audio/wav -> audio/x-float-array 
	at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:490)
	at com.ibm.watson.developer_cloud.service.WatsonService$2.execute(WatsonService.java:254)
```

i also try it via curl, but with same error
```
$ curl -X POST -u username:password --header "Content-Type: audio/wav" --header "Transfer-Encoding: chunked" --data-binary @src/test/resources/sample1.wav "https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?continuous=true"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80996    0   139  100 80902      2   1679  0:00:48  0:00:48 --:--:--     0{
   "code_description": "Bad Request",
   "code": 400,
   "error": "unable to transcode data stream audio/wav -> audio/x-float-array "
}

```

any suggestion or help?

**Comment by germanattanasio** [comment]
Hi @aximo,

I just tested the `recognize()` method with the `sample1.wav` file in this repository and its working fine.

**Code:**
```java
service = new SpeechToText("username", "password");
SpeechResults results = service.recognize(new File("sample1.wav")).execute();
System.out.println(results);
```

**Response:**
```json
{
  "result_index": 0,
  "results": [
    {
      "final": true,
      "alternatives": [
        {
          "confidence": 0.995,
          "transcript": "thunderstorms could produce large hail isolated tornadoes and heavy rain "
        }
      ]
    }
  ]
}
```

Can you try again?

**Comment by aximo** [comment]
the same error is still existed, I use the sample1.wav at

https://github.com/watson-developer-cloud/java-sdk/blob/master/speech-to-text/src/test/resources/speech_to_text/sample1.wav

but it seems that the file format is not  right,
