### ISSUE TITLE
Speech to text service launch a session time out when audio input stream is stopped using web sockets

### ISSUE THREAD

**Issue by fabriziopisciottaibm** [watson-developer-cloud/java-sdk#782]
Basically I would like to stop the streaming after I receive a recognized text to call another api, and then start again when i process the response from that api. The reason i am doing this is to avoid sending audio to the service continously. The error I'm getting is as follows:

```
Aug 31, 2017 3:35:54 PM com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.BaseRecognizeCallback onError
SEVERE: Session timed out.
java.lang.RuntimeException: Session timed out.
	at com.ibm.watson.developer_cloud.speech_to_text.v1.websocket.WebSocketManager$SpeechToTextWebSocketListener.onMessage(WebSocketManager.java:140)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lpatino10** [comment]
Would you be able to provide more of your code to give more context into what the problem might be? It's possible that the connection is not being closed properly, but I can't tell based on what you've written.

**Comment by germanattanasio** [comment]
closing due to inactivity
