### ISSUE TITLE
[Conversation] Output.getText() gives error Expected STRING but was BEGIN_ARRAY 

### ISSUE THREAD

**Issue by MJonker** [watson-developer-cloud/java-sdk#846]
I am running version : 4.2.1 of the SDK

When parsing this response:

```
{
  "output": {
    "text": [
      [
        {
          "intent": "informationProducts",
          "confidence": 0.9373455047607422
        },
        {
          "intent": "anything_else",
          "confidence": 0.31108554601669314
        },
        {
          "intent": "jobs",
          "confidence": 0.29402266740798955
        },
        {
          "intent": "goodbyes",
          "confidence": 0.2604020059108734
        },
        {
          "intent": "ServiceManagementMisc",
          "confidence": 0.22803921103477479
        },
        {
          "intent": "companyDetails",
          "confidence": 0.22541056871414186
        },
        {
          "intent": "aboutUs",
          "confidence": 0.21302702724933625
        }
      ],
      {
        "output": {
          "text": {
            "values": [
              "I am sorry I don't understand you. I have to learn a lot of new things here",
              "What do you mean? Enter a more specific question I am just a stupid bot"
            ],
            "selection_policy": "random"
          }
        }
      }
    ],
    "nodes_visited": [
      "node_5_1481641186803",
      "node_2_1481639717633"
    ],
    "log_messages": []
  },
  "input": {
    "text": "which products do you sell ?"
  },
  "intents": [
    {
      "intent": "informationProducts",
      "confidence": 0.9373455047607422
    }
  ],
  "entities": [],
  "context": {
    "system": {
      "dialog_stack": [
        {
          "dialog_node": "root"
        }
      ],
      "dialog_turn_counter": 3.0,
      "dialog_request_counter": 3.0,
      "_node_output_map": {
        "node_5_1481641186803": [
          0.0
        ]
      },
      "branch_exited": true,
      "branch_exited_reason": "completed"
    },
    "conversation_id": "1541a5a5-43f1-4241-a933-b2441ea97fc7",
    "username": "hi-2",
    "ConfidenceRef": "intents[0].confidence",
    "skip_user_input": true
  }
}

```
**Versus an output that is smaller:**
```
{
  "output": {
    "text": [
      "Hi hi-2, nice to meet you.  I am here to answer questions about e-office. What can I help you with?"
    ],
    "nodes_visited": [
      "node_1_1481017850147"
    ],
    "log_messages": []
  },
  "input": {
    "text": "hi-2"
  },
  "intents": [],
  "entities": [],
  "context": {
    "system": {
      "dialog_stack": [
        {
          "dialog_node": "root"
        }
      ],
      "dialog_turn_counter": 2.0,
      "dialog_request_counter": 2.0,
      "branch_exited": true,
      "branch_exited_reason": "completed"
    },
    "conversation_id": "cc278d11-09da-4ba5-9e47-5666b6095a9f",
    "username": "hi-2"
  }
}
```

**Comment by MJonker** [comment]
I am using version: 2017-05-26 of the Conversation Service

**Comment by lpatino10** [comment]
Would you be able to post a stack trace of the error? This will help identify exactly where the problem is coming from.

**Comment by MJonker** [comment]
StackTrace below
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $[0]
	at com.google.gson.Gson.fromJson(Gson.java:900)
	at com.google.gson.Gson.fromJson(Gson.java:953)
	at com.ibm.watson.developer_cloud.util.GsonSerializationHelper.serializeDynamicModelProperty(GsonSerializationHelper.java:29)
	at com.ibm.watson.developer_cloud.conversation.v1.model.OutputData.getText(OutputData.java:48)
	at nl.eoffice.google.action.talktoeoffice.StandAloneClient.main(StandAloneClient.java:64)
Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $[0]
	at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:180)
```

**Comment by MJonker** [comment]
I understand that this is an edge case, but since the Watson Conversation Service is capable of producing this output, I hope you can fix this ?

**Comment by germanattanasio** [comment]
`output` used to be something like
```json
"output": {
  "text": ["...","..."],
}
```

but now it's 

```json
"output": {
  "text": {
    "values": ["...","..."],
    "selection": "random"
  }
}
```

**Comment by germanattanasio** [comment]
Which `version_date` are you using?

**Comment by MJonker** [comment]
I tried all but the we want to use : .VERSION_DATE_2017_05_26.
But I think this really is an edge case, we only get this for this conversation we have not touched in a while. So this was more a letting you know kind of issue, than a "must be fixed" :-)

**Comment by germanattanasio** [comment]
I checked with the team, and this seems to be due to how you reply to the `output.text` to users. By default, it is an array of strings, but you can change that when you design your dialog

**Comment by MJonker** [comment]
ok let's close this issue then..
