### ISSUE TITLE
[discovery] java.lang.StackOverflowError when executing query with more then one aggr egation.

### ISSUE THREAD

**Issue by RogerioBaldiniIBM** [watson-developer-cloud/java-sdk#854]
When executing this aggregation query:
```
nested(enriched_text.entities).filter(enriched_text.entities.type::"Company").term(enriched_text.entities.text,count:100)

returns: 

java.lang.StackOverflowError: null
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:787)
	at com.ibm.watson.developer_cloud.discovery.v1.query.AggregationDeserializer.parseNext(AggregationDeserializer.java:109)
	at com.ibm.watson.developer_cloud.discovery.v1.query.AggregationDeserializer.parseObject(AggregationDeserializer.java:171)
	at com.ibm.watson.developer_cloud.discovery.v1.query.AggregationDeserializer.parseNext(AggregationDeserializer.java:118)
	at com.ibm.watson.developer_cloud.discovery.v1.query.AggregationDeserializer.parseArray(AggregationDeserializer.java:150)
```

Version 4.2.1
Thanks.

**Comment by germanattanasio** [comment]
There is currently a limitation where queries can only be up to 2000 characters. make sure your query is not longer than that

**Comment by germanattanasio** [comment]
Related to #835

**Comment by RogerioBaldiniIBM** [comment]
I am sure my query is no longer then 2000 caracteres...

**Comment by germanattanasio** [comment]
Please provide a set of reproducible steps. Check the CONTRIBUTING.md for an example.

**Comment by lpatino10** [comment]
Thanks for submitting this issue @RogerioBaldiniIBM.

Right now, the Java SDK only supports the following query aggregations: max, min, average, sum, histogram, and term. Unfortunately, attempting to use unsupported aggregations causes the program to crash, as you've realized.

I'll start work on supporting the rest of the aggregations and adding a working default aggregation for any future unsupported types.
