### ISSUE TITLE
updateProfile method sometimes throws com.ibm.watson.developer_cloud.service.NotFoundException

### ISSUE THREAD

**Issue by aarora91** [watson-developer-cloud/java-sdk#86]
The exception is thrown sometimes and sometimes it works fine with the same input and dialogid.  
**Stack trace:**
```
com.ibm.watson.developer_cloud.service.NotFoundException: The dialog_id specified is invalid or does not exist. Include a valid dialog_id on the URL. 
at com.ibm.watson.developer_cloud.service.WatsonService.execute(WatsonService.java:193) 
at com.ibm.watson.developer_cloud.service.WatsonService.executeWithoutResponse(WatsonService.java:244) 
at com.ibm.watson.developer_cloud.dialog.v1.DialogService.updateProfile(DialogService.java:428) 
// Internal classes
```

**Comment by germanattanasio** [comment]
Hi @aarora91, I did some testing and seems like the problem is in the API. I was able to reproduce the issue while sending multiple requests to the same dialog.

The current workaround is to wait ~.5 seconds between API calls.
