### ISSUE TITLE
[text-to-speech] Call service with AudioFormat.WEBM_OPUS

### ISSUE THREAD

**Issue by elvists** [watson-developer-cloud/java-sdk#905]
When executing this aggregation query:
> service.synthesize(text, Voice.PT_ISABELA, AudioFormat.WEBM_OPUS).execute();

> D/OkHttp: <-- 400 Bad Request https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=pt-BR_IsabelaVoice&accept=audio/webm;%20codecs%3Dopus (630ms, unknown-length body)
E/WatsonService: POST https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=pt-BR_IsabelaVoice&accept=audio/webm;%20codecs%3Dopus, status: 400, error: The query arguments [' codecs=opus'] must not be empty in voice=pt-BR_IsabelaVoice&+codecs%3Dopus=&accept=audio/webm%3B+codecs%3Dopus
E/Erro: The query arguments [' codecs=opus'] must not be empty in voice=pt-BR_IsabelaVoice&+codecs%3Dopus=&accept=audio/webm%3B+codecs%3Dopus
        com.ibm.watson.developer_cloud.service.exception.BadRequestException: The query arguments [' codecs=opus'] must not be empty in voice=pt-BR_IsabelaVoice&+codecs%3Dopus=&accept=audio/webm%3B+codecs%3Dopus
            at com.ibm.watson.developer_cloud.service.WatsonService.processServiceCall(WatsonService.java:408)
            at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:174)
            at br.com.sabesp.chatbot.service.WatsonTextToSpeechService.falar(WatsonTextToSpeechService.java:36)
            at br.com.sabesp.chatbot.service.WatsonTextToSpeechService.doInBackground(WatsonTextToSpeechService.java:46)
            at br.com.sabesp.chatbot.service.WatsonTextToSpeechService.doInBackground(WatsonTextToSpeechService.java:20)
            at android.os.AsyncTask$2.call(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            at java.lang.Thread.run(Thread.java:762)

Version 4.2.1

I upgraded to the new version and changed a few things and it worked.

I think the problem may be because of the space empty in the String "AUDIO_WEBM_OPUS" after of "audio/webm;" (in the version 4.2.1):

AudioFormat
`public static final AudioFormat WEBM_OPUS = new AudioFormat(HttpMediaType.AUDIO_WEBM_OPUS); `
...
HttpMediaType
`public static final String AUDIO_WEBM_OPUS = "audio/webm; codecs=opus";`

in the version 5.1.1

SynthesizeOptions
 `
String AUDIO_WEBM_CODECS_OPUS = "audio/webm;codecs=opus";`

**Comment by lpatino10** [comment]
Hey @elvists, thanks for bringing this issue to light. It does seem that the space in the audio format was causing issues, since it was being passed as a query parameter.

As you've noticed, this has been fixed in versions >5.0 as the audio format is now always passed as a header. I've tested with and without the space and both work with the latest version.

I'm going to close this issue as it's been fixed, but this might be helpful for anyone running into this issue on an old version.
