### ISSUE TITLE
Socket Exception: Connection reset Exception.

### ISSUE THREAD

**Issue by EKInnovationLab** [watson-developer-cloud/java-sdk#965]
We have observed sometimes we are not getting response from IBM Watson conversation service API. We checked logs and found Socket Exception: Connection reset Exception. Below are the logs for reference.

JDK Version used: 1.8
code snippet

```java
ConversationService service = new ConversationService(ConversationService.VERSION_DATE_2016_07_11);
service.setUsernameAndPassword(
  environment.getProperty("watson-conv-username"),
  environment.getProperty("watson-conv-password")
);
		
MessageRequest newWatsonMessage = new MessageRequest.Builder()
  .inputText(watsonRequestDto.getMessage())
  .context(watsonRequestDto.getContext())
  .build();
watsonResponse = service.message(
  environment.getProperty("watson-workspace-id-payment"), 
  newWatsonMessage
).execute();
```

Logs:

```
2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.web.servlet.DispatcherServlet-DispatcherServlet with name 'dispatcherServlet' processing POST request for [/bots/api/watsonconv/conversation/]

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.w.s.m.m.a.RequestMappingHandlerMapping-Looking up handler method for path /bots/api/watsonconv/conversation/

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.w.s.m.m.a.RequestMappingHandlerMapping-Returning handler method [private com.ibm.watson.developer_cloud.conversation.v1.model.MessageResponse com.emirates.chatbot.watsonconv.controller.watsonconvcontroller.getWatsonResponse(com.emirates.chatbot.watsonconv.dto.WatsonRequestDto)]

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.w.s.m.m.a.RequestResponseBodyMethodProcessor-Read [class com.emirates.chatbot.watsonconv.dto.WatsonRequestDto] as "application/json;charset=UTF-8" with [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@5fd4f8f5]

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.w.s.m.m.a.ExceptionHandlerExceptionResolver-Resolving exception from handler [private com.ibm.watson.developer_cloud.conversation.v1.model.MessageResponse com.emirates.chatbot.watsonconv.controller.watsonconvcontroller.getWatsonResponse(com.emirates.chatbot.watsonconv.dto.WatsonRequestDto)]: java.lang.RuntimeException: java.net.SocketException: Connection reset

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.w.s.m.a.ResponseStatusExceptionResolver-Resolving exception from handler [private com.ibm.watson.developer_cloud.conversation.v1.model.MessageResponse com.emirates.chatbot.watsonconv.controller.watsonconvcontroller.getWatsonResponse(com.emirates.chatbot.watsonconv.dto.WatsonRequestDto)]: java.lang.RuntimeException: java.net.SocketException: Connection reset

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.w.s.m.s.DefaultHandlerExceptionResolver-Resolving exception from handler [private com.ibm.watson.developer_cloud.conversation.v1.model.MessageResponse com.emirates.chatbot.watsonconv.controller.watsonconvcontroller.getWatsonResponse(com.emirates.chatbot.watsonconv.dto.WatsonRequestDto)]: java.lang.RuntimeException: java.net.SocketException: Connection reset

2018-06-26 13:30:15 [http-nio-8105-exec-6] DEBUGo.s.web.servlet.DispatcherServlet-Could not complete request

java.lang.RuntimeException: java.net.SocketException: Connection reset

                at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:181)

                at com.emirates.chatbot.watsonconv.controller.watsonconvcontroller.getWatsonResponse(watsonconvcontroller.java:136)

                at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.lang.reflect.Method.invoke(Method.java:498)

                at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)

                at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)

                at

Caused by: java.net.SocketException: Connection reset

                at java.net.SocketInputStream.read(SocketInputStream.java:210)

                at java.net.SocketInputStream.read(SocketInputStream.java:141)

                at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)

                at sun.security.ssl.InputRecord.read(InputRecord.java:503)

                at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)

                at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)

                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)

                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)

                at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)

                at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)

                at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)

                at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)

                at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)

                at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)

                at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)

                at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)

                at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)

                at okhttp3.RealCall.getResponse(RealCall.java:243)

                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)

                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)

                at okhttp3.RealCall.execute(RealCall.java:57)

                at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:178)

                ... 66 common frames omitted

2018-06-26 13:30:15 [http-nio-8105-exec-6] ERRORo.a.c.c.C.[.[.[.[dispatcherServlet]-Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.net.SocketException: Connection reset] with root cause

java.net.SocketException: Connection reset

                at java.net.SocketInputStream.read(SocketInputStream.java:210)

                at java.net.SocketInputStream.read(SocketInputStream.java:141)

                at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)

                at sun.security.ssl.InputRecord.read(InputRecord.java:503)

                at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)

                at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)

                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)

                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)

                at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)

                at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)

                at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)

                at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)

                at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)

                at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)

                at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)

                at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)

                at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)

                at okhttp3.RealCall.getResponse(RealCall.java:243)

                at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)

                at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)

                at okhttp3.RealCall.execute(RealCall.java:57)

                at com.ibm.watson.developer_cloud.service.WatsonService$1.execute(WatsonService.java:178)

                at com.emirates.chatbot.watsonconv.controller.watsonconvcontroller.getWatsonResponse(watsonconvcontroller.java:136)

                at sun.reflect.GeneratedMethodAccessor107.invoke(Unknown Source)

                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

                at java.lang.reflect.Method.invoke(Method.java:498)

                at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)

                at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)

                at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)

                at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)

                at
```

**Comment by germanattanasio** [comment]
This is not a problem in the SDK but an issue with the service. `Connection reset` means the other side of the TCP conversation abruptly closed its end of the connection.

**Comment by germanattanasio** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a set of reproducible steps. Check the CONTRIBUTING.md for an example.
