### ISSUE TITLE
[discovery_data_crawler] InvalidKeySpecException occurred when using Discovery data crawler with Box.

### ISSUE THREAD

**Issue by devzip8** [watson-developer-cloud/java-sdk#976]
I would like to crawl BOX and upload files to Discovery by using the Data Crawler.
I reffered to the link below and configured BOX crawl options.

https://console.bluemix.net/docs/services/discovery/data-crawler-seeds.html#configuring-connector-and-seed-options

When I executed "crawler testit" cmd, the following error happend.
(Some Japanese are included.)

At first, I asked IBM Cloud support.
They confirmed the following log and my box.conf and they thought it seemedd to be no problem.
Then, They told me to create an issue here.

We use CentOS Linux release 7.5.1804 (Core) and Java 1.8.0_171.

```
[root@localhost crawl]# crawler testit
2018-07-27 13:03:31,003 INFO: Connector Framework サービスが開始され、ポート 43548 上のクローラーに接続されます
2018-07-27 13:03:31,491 INFO: このクロールは Test-It モードで実行されています
2018-07-27 13:03:31,491 INFO: 構成されたシードに一致する場合、構成された出力アダプターに最大 1 つの項目が送信されます。
2018-07-27 13:03:31,491 INFO: シードが処理された後、それ以後にエンキューされた最大 5 の URL が表示されますが、取得されません。
2018-07-27 13:03:31,492 INFO: クロールを実行しています...
2018-07-27 13:03:31,494 INFO: 次のパターンと一致する URL は処理されません: (?i)\.(xlsx?|pptx?|jpe?g|gif|png|mp3|tiff)$
2018-07-27 13:03:31,541 INFO: HikariPool-1 - Starting...
2018-07-27 13:03:31,756 INFO: HikariPool-1 - Start completed.
java.security.spec.InvalidKeySpecException: Inappropriate key specification: algid parse error, not a sequence
	at com.ibm.crypto.provider.RSAKeyFactory.engineGeneratePrivate(Unknown Source)
	at java.security.KeyFactory.generatePrivate(KeyFactory.java:383)
	at com.ibm.dataexplorer.connectors.box.auth.BoxJWTAssertionProcess.getPrivateKey(BoxJWTAssertionProcess.scala:116)
	at com.ibm.dataexplorer.connectors.box.auth.BoxJWTAssertionProcess.getJWTAssertion(BoxJWTAssertionProcess.scala:94)
	at com.ibm.dataexplorer.connectors.box.auth.BoxJWTAssertionProcess.getToken(BoxJWTAssertionProcess.scala:59)
	at com.ibm.dataexplorer.connectors.box.BoxAPI.initialize(BoxAPI.scala:96)
	at com.ibm.dataexplorer.connectors.box.auth.BoxInitialize.<init>(BoxInitialize.scala:48)
	at com.ibm.dataexplorer.connectors.box.auth.BoxInitialize$$FastClassByGuice$$3e4e1182.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:111)
	at com.google.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:811)
	at com.google.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at com.google.inject.Scopes$1$1.get(Scopes.java:54)
	at com.google.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:48)
	at com.google.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at com.google.inject.InjectorBuilder$1.call(InjectorBuilder.java:194)
	at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:804)
	at com.google.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:194)
	at com.google.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:176)
	at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:92)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.ibm.dataexplorer.connector.extensions.inject.GuiceLifeCycleListener.createRootInjector(GuiceLifeCycleListener.java:187)
	at com.ibm.dataexplorer.connector.extensions.inject.GuiceLifeCycleListener.beforeCrawlStarted(GuiceLifeCycleListener.java:175)
	at com.vivisimo.connector.internal.event.StandardLifeCycleEventDispatcher.fireBeforeCrawlStartedEvent(StandardLifeCycleEventDispatcher.java:80)
	at com.vivisimo.connector.internal.Runner.runThreads(Runner.java:140)
	at com.vivisimo.connector.ConnectorRunner.main(ConnectorRunner.java:123)
com.ibm.dataexplorer.connector.extensions.inject.GuiceLifeCycleListener$RootInjectorCreationFailed: com.google.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Key argument cannot be null.
  at com.ibm.dataexplorer.connectors.box.auth.BoxInitialize.<init>(BoxInitialize.scala:29)
  while locating com.ibm.dataexplorer.connectors.box.auth.BoxInitialize

1 error
	at com.ibm.dataexplorer.connector.extensions.inject.GuiceLifeCycleListener.createRootInjector(GuiceLifeCycleListener.java:189)
	at com.ibm.dataexplorer.connector.extensions.inject.GuiceLifeCycleListener.beforeCrawlStarted(GuiceLifeCycleListener.java:175)
	at com.vivisimo.connector.internal.event.StandardLifeCycleEventDispatcher.fireBeforeCrawlStartedEvent(StandardLifeCycleEventDispatcher.java:80)
	at com.vivisimo.connector.internal.Runner.runThreads(Runner.java:140)
	at com.vivisimo.connector.ConnectorRunner.main(ConnectorRunner.java:123)
Caused by: com.google.inject.CreationException: Guice creation errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Key argument cannot be null.
  at com.ibm.dataexplorer.connectors.box.auth.BoxInitialize.<init>(BoxInitialize.scala:29)
  while locating com.ibm.dataexplorer.connectors.box.auth.BoxInitialize

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:354)
	at com.google.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:179)
	at com.google.inject.InjectorBuilder.build(InjectorBuilder.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:92)
	at com.google.inject.Guice.createInjector(Guice.java:69)
	at com.ibm.dataexplorer.connector.extensions.inject.GuiceLifeCycleListener.createRootInjector(GuiceLifeCycleListener.java:187)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Key argument cannot be null.
	at io.jsonwebtoken.lang.Assert.notNull(Assert.java:80)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:113)
	at com.ibm.dataexplorer.connectors.box.auth.BoxJWTAssertionProcess.getJWTAssertion(BoxJWTAssertionProcess.scala:107)
	at com.ibm.dataexplorer.connectors.box.auth.BoxJWTAssertionProcess.getToken(BoxJWTAssertionProcess.scala:59)
	at com.ibm.dataexplorer.connectors.box.BoxAPI.initialize(BoxAPI.scala:96)
	at com.ibm.dataexplorer.connectors.box.auth.BoxInitialize.<init>(BoxInitialize.scala:48)
	at com.ibm.dataexplorer.connectors.box.auth.BoxInitialize$$FastClassByGuice$$3e4e1182.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:111)
	at com.google.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:45)
	at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:811)
	at com.google.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:42)
	at com.google.inject.Scopes$1$1.get(Scopes.java:54)
	at com.google.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:48)
	at com.google.inject.InjectorBuilder$1.call(InjectorBuilder.java:200)
	at com.google.inject.InjectorBuilder$1.call(InjectorBuilder.java:194)
	at com.google.inject.InjectorImpl.callInContext(InjectorImpl.java:804)
	at com.google.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:194)
	at com.google.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:176)
	... 8 more
2018-07-27 13:03:33,909 ERROR: クロールの実行中に致命的な例外を受け取りました: 
Connection reset
クローラーを完全にシャットダウンしようとしています。
Checking Java version since crawler exited irregularly...
Your Java version is 1.8.0_171, which Crawler supports. Inspect logging output for errors.
...
```

Next, I'll attach the content of box.conf
```
crawl_extender {
  attribute = [
    {
      name="protocol",
      value="box"
    },
    {
      name="collection",
      value="Box ogosy"
    },
    {
      name="dns",
      value="dns"
    }
  ],
  all_crawl_options {
    crawl_extender_options = [
      {
        name="classname",
        data="plugin:box.plugin@connector"
      },
      {
        name = "logging-config",
        data = "<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'/>"
      },
      {
        # The base URL
        # This probably shouldn't change.
        name="box-crawl-seed-url",
        value="box://app.box.com/"
      },
      {
        name="client-id",
        value="******46hmbbv31q1ji54krujte0******"  # I masked
      },
      {
        name="client-secret",
        value="******5N1Hd1ZYkqZEOSUCnJoB******" # I masked 
      },
      {
        name="path-to-private-key",
        value="/tmp/crawl/private-key2.der"
      },
      {
        name="kid",
        value="*******" # I masked 
      },
      {
        name="enterprise-id",
        value="********" # I masked
      }
      
    ],
    curl_options = [
      {
        name="enable-acl",
        data="true"
      },
      {
        name="user-agent",
        data="IBM Watson Data Crawler/1.x"
      },
      {
        name="method",
        data="GET"
      },
      {
        name="url-logging",
        data="refined-logging"
      },
      {
        name="ssl-version",
        data="TLSv1"
      },
      {
      # test it mode
      # change this to 1 if you want to run a test-it
        name="test-it-mode",
        data="1"
      }
    ]
  }
}
```
Sincerly,

**Comment by germanattanasio** [comment]
@bruceadams do you know someone that can help with the issue above?
It's not a problem in the SDK.

**Comment by bruceadams** [comment]
Yes. I'll get the more eyes on this question.

An alternate that I strongly recommend using is the new _Connecting to Data Sources_ feature in Discovery, see: https://console.bluemix.net/docs/services/discovery/connect.html#connectbox

**Comment by devzip8** [comment]
Thanks for your information.
I referred to the URL and finally I could crawl files from Box into Discovery.
Because I have new questions about the behaviour of crawling, I'll ask IBM Cloud support again.
I close this issue.
Thank you.

Sincierly,
