### ISSUE TITLE
Another 'Unable to find acceptable protocols.' error

### ISSUE THREAD

**Issue by rball1** [watson-developer-cloud/java-sdk#992]
I'm using the latest Watson java SDK (6.0) in a web service to communicate with Watson Assistant. Running in WAS version 9. This was working before the change of Watson to TLS1.2
I get the following error:
```
[10/8/18 11:36:05:027 EDT] 000000a3 SystemErr     R java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[TLSv1]
[10/8/18 11:36:05:029 EDT] 000000a3 SystemErr     R     at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73)
[10/8/18 11:36:05:029 EDT] 000000a3 SystemErr     R     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:274)
[10/8/18 11:36:05:030 EDT] 000000a3 SystemErr     R     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
```

I've enables TLS1.2 in WAS and tried various ConnectionSpec settings.
```java
	         ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS).tlsVersions(TlsVersion.TLS_1_2)
	        		.cipherSuites(CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
	                 CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
	                 CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
	                 CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
	                 CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
	                 CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
	                 CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
	                 CipherSuite.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
	                 CipherSuite.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
	                 CipherSuite.TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
	                 CipherSuite.TLS_DHE_DSS_WITH_AES_128_CBC_SHA,
	                 CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA).build();
```

**Comment by germanattanasio** [comment]
Check doing something like this: https://github.com/cloudant/java-cloudant/pull/220/files and setting the http client configuration in the watson service class

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
